# GitHub Pages Configuration for SPA routing
include:
  - "_*"
  
plugins:
  - jekyll-redirect-from

# Ensure all routes are handled by index.html
defaults:
  - scope:
      path: ""
    values:
      layout: false
